import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans antialiased">
      <body className={inter.className}>
        <Header />
        <main className="flex min-h-[calc(100dvh-150px)] flex-col items-center justify-start p-10 gap-10">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
